/* ==================================
 Project: hyprhub
 Author: grid
 Description: Hyprland configuration
================================== */

# #######################
# Font
# #######################

font_family      JetBrainsMono Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto

font_size 13.5

# #######################
# Window
# #######################

background_opacity 0.82
background_blur 35

window_padding_width 12

hide_window_decorations yes
confirm_os_window_close 0

# #######################
# Cursor
# #######################

cursor_shape beam
cursor_blink_interval 0.5
cursor_stop_blinking_after 15

# #######################
# Scrollback
# #######################

scrollback_lines 10000
wheel_scroll_multiplier 5

# #######################
# Performance
# #######################

enable_audio_bell no
visual_bell_duration 0

repaint_delay 8
input_delay 0
sync_to_monitor yes

# #######################
# Selection
# #######################

copy_on_select yes
strip_trailing_spaces smart

# #######################
# Tab Bar
# #######################

tab_bar_edge top
tab_bar_style powerline

tab_separator " ┇ "
tab_powerline_style slanted

active_tab_font_style bold

# #######################
# Colors
# #######################

foreground #CDD6F4
background #11111B
selection_foreground #11111B
selection_background #A6ADC8

cursor #F5E0DC
cursor_text_color background

color0  #45475A
color1  #F38BA8
color2  #A6E3A1
color3  #F9E2AF
color4  #89B4FA
color5  #F5C2E7
color6  #94E2D5
color7  #BAC2DE

color8  #585B70
color9  #F38BA8
color10 #A6E3A1
color11 #F9E2AF
color12 #89B4FA
color13 #F5C2E7
color14 #94E2D5
color15 #A6ADC8

# #######################
# URLs
# #######################

underline_hyperlinks always

# #######################
# Misc
# #######################

shell_integration enabled
allow_remote_control yes
