-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
-- AUTOGENERATED HYPRLAND CONFIG.                        --
-- PROFESSIONAL VERSION                                  --
-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
-- ----------------
-- -- MONITORS ----
-- ----------------
hl.monitor({
    output = "",
    mode = "preferred",
    position = "auto",
    scale = 1,
    transform = 0
})

-- -------------------
-- -- MY PROGRAMS ----
-- -------------------
local terminal = "kitty"
local fileManager = "thunar"
local menu = "anyrun"

-- -----------------
-- -- AUTOSTART ----
-- -----------------
hl.on("hyprland.start", function()
    hl.exec_cmd("waybar & swaync & swayosd-server &")
    hl.exec_cmd("waypaper --restore")
    hl.exec_cmd("wl-paste --type text --watch cliphist store")
end)

-- -----------------------------
-- -- ENVIRONMENT VARIABLES ----
-- -----------------------------
hl.env("XCURSOR_SIZE", "24")
hl.env("HYPRCURSOR_SIZE", "24")

-- ---------------------
-- -- LOOK AND FEEL ----
-- ---------------------
hl.config({
    general = {
        gaps_in = 3,
        gaps_out = 3,
        border_size = 2,
        col = {
            active_border = {
                colors = { "rgba(33ccffee)", "rgba(00ff99ee)" },
                angle = 45
            },
            inactive_border = "rgba(595959aa)"
        },
        resize_on_border = false,
        allow_tearing = false,
        layout = "dwindle"
    },

    decoration = {
        rounding = 10,
        rounding_power = 2,
        active_opacity = .9,
        inactive_opacity = .9,
        shadow = {
            enabled = true,
            range = 4,
            render_power = 3,
            color = 0xee1a1a1a
        },
        blur = {
            enabled = true,
            size = 8,
            passes = 0,
            vibrancy = 0.1696
        }
    },

    animations = {
        enabled = true
    }
})

-- --------------
-- -- LAYOUTS ---
-- --------------
hl.config({
    dwindle = {
        preserve_split = true
    },
    master = {
        new_status = "master"
    },
    scrolling = {
        fullscreen_on_one_column = true
    },
    misc = {
        force_default_wallpaper = -1,
        disable_hyprland_logo = false
    }
})

-- -------------
-- -- INPUT ----
-- -------------
hl.config({
    input = {
        kb_layout = "us",
        follow_mouse = 1,
        sensitivity = 0,
        touchpad = {
            natural_scroll = false
        }
    }
})

hl.gesture({
    fingers = 3,
    direction = "horizontal",
    action = "workspace"
})

-- -------------------
-- -- KEYBINDINGS ----
-- -------------------
local mainMod = "SUPER"

-- Asosiy boshqaruv
hl.bind(mainMod .. " + Return", hl.dsp.exec_cmd(terminal))
hl.bind(mainMod .. " + Q", hl.dsp.window.close())
hl.bind("SUPER + M", hl.dsp.exec_cmd("pkill Hyprland"))
hl.bind(mainMod .. " + E", hl.dsp.exec_cmd(fileManager))
hl.bind(mainMod .. " + L", hl.dsp.window.float({
    action = "toggle"
}))


-- Focus/Move
hl.bind(mainMod .. " + left", hl.dsp.focus({
    direction = "left"
}))
hl.bind(mainMod .. " + right", hl.dsp.focus({
    direction = "right"
}))
hl.bind(mainMod .. " + up", hl.dsp.focus({
    direction = "up"
}))
hl.bind(mainMod .. " + down", hl.dsp.focus({
    direction = "down"
}))

hl.bind(mainMod .. " + SHIFT + left", hl.dsp.window.move({
    direction = "left"
}))
hl.bind(mainMod .. " + SHIFT + right", hl.dsp.window.move({
    direction = "right"
}))
hl.bind(mainMod .. " + SHIFT + up", hl.dsp.window.move({
    direction = "up"
}))
hl.bind(mainMod .. " + SHIFT + down", hl.dsp.window.move({
    direction = "down"
}))

-- Workspaces
for i = 1, 10 do
    local key = i % 10
    hl.bind(mainMod .. " + " .. key, hl.dsp.focus({
        workspace = i
    }))
    hl.bind(mainMod .. " + SHIFT + " .. key, hl.dsp.window.move({
        workspace = i
    }))
end

-- Special Workspace
hl.bind(mainMod .. " + S", hl.dsp.workspace.toggle_special("magic"))
hl.bind(mainMod .. " + SHIFT + S", hl.dsp.window.move({
    workspace = "special:magic"
}))

-- Mouse & Multimedia
hl.bind(mainMod .. " + mouse_down", hl.dsp.focus({
    workspace = "e+1"
}))
hl.bind(mainMod .. " + mouse_up", hl.dsp.focus({
    workspace = "e-1"
}))
hl.bind(mainMod .. " + mouse:272", hl.dsp.window.drag(), {
    mouse = true
})
hl.bind(mainMod .. " + mouse:273", hl.dsp.window.resize(), {
    mouse = true
})

-- volume

hl.bind("XF86AudioRaiseVolume",
    hl.dsp.exec_cmd("wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+ && swayosd-client --output-volume raise"), {
        locked = true,
        repeating = true
    })

hl.bind("XF86AudioLowerVolume",
    hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%- && swayosd-client --output-volume lower"), {
        locked = true,
        repeating = true
    })

hl.bind("XF86AudioMute", hl.dsp.exec_cmd([[
sh -c '
wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle

if wpctl get-volume @DEFAULT_AUDIO_SINK@ | grep -q MUTED; then
    swayosd-client --output-volume mute
else
    swayosd-client --output-volume unmute
fi
'
]]), {
    locked = true,
    repeating = false
})

-- Brightness

hl.bind("XF86MonBrightnessUp", hl.dsp.exec_cmd("brightnessctl set 5%+ && swayosd-client --brightness raise"), {
    locked = true,
    repeating = true
})

hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("brightnessctl set 5%- && swayosd-client --brightness lower"), {
    locked = true,
    repeating = true
})

hl.window_rule({
    name = "games-no-opacity",
    match = {
        fullscreen = true
    },
    opacity = "1.0 1.0"
})





-- ------------------------------
-- -- WINDOWS AND WORKSPACES ----
-- ------------------------------
hl.window_rule({
    name = "suppress-maximize-events",
    match = {
        class = ".*"
    },
    suppress_event = "maximize"
})

hl.window_rule({
    name = "move-hyprland-run",
    match = {
        class = "hyprland-run"
    },
    move = "20 monitor_h-120",
    float = true
})

-- Curves
hl.curve("smooth", {
    type = "bezier",
    points = { { 0.22, 1 }, { 0.36, 1 } }
})

hl.curve("smoothFast", {
    type = "bezier",
    points = { { 0.18, 1 }, { 0.32, 1 } }
})

hl.curve("soft", {
    type = "bezier",
    points = { { 0.25, 0.95 }, { 0.35, 1 } }
})

hl.curve("snappy", {
    type = "spring",
    mass = 0.85,
    stiffness = 320,
    dampening = 28
})

hl.curve("ultra", {
    type = "spring",
    mass = 1,
    stiffness = 280,
    dampening = 26
})

-- Animations
hl.animation({
    leaf = "global",
    enabled = true,
    speed = 12,
    bezier = "default"
})

hl.animation({
    leaf = "border",
    enabled = true,
    speed = 7,
    bezier = "smooth"
})

hl.animation({
    leaf = "windows",
    enabled = true,
    speed = 6,
    spring = "snappy"
})

hl.animation({
    leaf = "windowsIn",
    enabled = true,
    speed = 5.5,
    spring = "ultra",
    style = "popin 92%"
})

hl.animation({
    leaf = "windowsOut",
    enabled = true,
    speed = 2.5,
    bezier = "smoothFast",
    style = "popin 92%"
})

hl.animation({
    leaf = "fade",
    enabled = true,
    speed = 5,
    bezier = "soft"
})

hl.animation({
    leaf = "fadeIn",
    enabled = true,
    speed = 2.8,
    bezier = "soft"
})

hl.animation({
    leaf = "fadeOut",
    enabled = true,
    speed = 2.2,
    bezier = "soft"
})

hl.animation({
    leaf = "layers",
    enabled = true,
    speed = 5,
    bezier = "smooth"
})

hl.animation({
    leaf = "layersIn",
    enabled = true,
    speed = 5,
    bezier = "smooth",
    style = "fade"
})

hl.animation({
    leaf = "layersOut",
    enabled = true,
    speed = 2,
    bezier = "smoothFast",
    style = "fade"
})

hl.animation({
    leaf = "fadeLayersIn",
    enabled = true,
    speed = 2.6,
    bezier = "soft"
})

hl.animation({
    leaf = "fadeLayersOut",
    enabled = true,
    speed = 2,
    bezier = "soft"
})

hl.animation({
    leaf = "workspaces",
    enabled = true,
    speed = 3.5,
    spring = "ultra",
    style = "slidefade"
})

hl.animation({
    leaf = "workspacesIn",
    enabled = true,
    speed = 3,
    spring = "ultra",
    style = "slidefade"
})

hl.animation({
    leaf = "workspacesOut",
    enabled = true,
    speed = 2.5,
    spring = "ultra",
    style = "slidefade"
})

hl.animation({
    leaf = "zoomFactor",
    enabled = true,
    speed = 8,
    bezier = "smoothFast"
})
